version: 2.1

jobs:
  lint-docker:
    docker:
      - image: hadolint/hadolint:latest-debian
    steps:
      - checkout
      - run:
          name: Lint docker/api/Dockerfile
          command: hadolint docker/app/Dockerfile
      - run:
          name: Lint docker/api/Dockerfile
          command: hadolint docker/app/Dockerfile

  build:
    docker:
      - image:  circleci/node:12.16.3
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Build app
          command: npm install --prefix ./app
      - run:
          name: Build api
          command: npm install --prefix ./api
      - persist_to_workspace:
          root: ~/project
          paths:
            - app/node_modules
            - api/node_modules

  lint:
    docker:
      - image:  circleci/node:12.16.3
    steps:
      - checkout
      - run:
          name: Build app
          command: npm install --prefix ./app
      - run:
          name: Build api
          command: npm install --prefix ./api
      - run:
          name: Lint app
          command: ~/project/app/node_modules/.bin/eslint ~/project/app
      - run:
          name: Lint api
          command: ~/project/api/node_modules/.bin/eslint ~/project/api


workflows:
  version: 2

  build:
    jobs:
      - build
      - lint-docker
      - lint:
          requires:
            - build
